### ISSUE TITLE
Problems with readme links

### ISSUE THREAD

**Issue by michalmuskala** [2Latinos/nuntius#43] opened 2022-05-24 12:34 UTC
The link to documentation leads to https://hexdocs.pm/nuntius/, which results in 404 Page not found.

The link to examples leads to https://github.com/2Latinos/nuntius/blob/main/examples, which also results in 404 Page not found

**Comment by paulo-ferraz-oliveira** [comment] 2022-05-24 14:43
Hey, @michalmuskala, thanks for the report.

We were aware the `examples` where not available (since they haven't yet been coded), but not the other one (I guess we either didn't push the doc. explicitly or assumed it would 😄).

Let me get to this when I have some time.

**Comment by paulo-ferraz-oliveira** [comment] 2023-10-29 11:43
Closing as duplicate of #10. When we add code examples this issue should be handled. Also, `ex_doc` was not complaining about broken links, but [it has been fixed](https://github.com/elixir-lang/ex_doc/pull/1798).

**Closed by paulo-ferraz-oliveira** 2023-10-29 11:43 UTC
